<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Manjari Kannan">
<meta name="author" content="Nicholas Decesaris">
<meta name="author" content="Oscar Quintero">
<meta name="dcterms.date" content="2026-04-13">

<title>Career Strategy – Job Market Analysis 2024</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-4897d45d2f75ed4f519693be625836c5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Job Market Analysis 2024</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./introduction.html"> 
<span class="menu-text">Project Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data_cleaning.html"> 
<span class="menu-text">Data Preparation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./eda.html"> 
<span class="menu-text">Exploratory Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ml_methods.html"> 
<span class="menu-text">Predictive Modeling</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./skill_gap_analysis.html"> 
<span class="menu-text">Skill Gap Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./career_plan.html"> 
<span class="menu-text">Career Strategy</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#objective" id="toc-objective" class="nav-link active" data-scroll-target="#objective">Objective</a></li>
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">Research Question</a></li>
  <li><a href="#why-this-matters" id="toc-why-this-matters" class="nav-link" data-scroll-target="#why-this-matters">Why This Matters</a></li>
  <li><a href="#planned-analysis" id="toc-planned-analysis" class="nav-link" data-scroll-target="#planned-analysis">Planned Analysis</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  <li><a href="#overview" id="toc-overview" class="nav-link" data-scroll-target="#overview">Overview</a></li>
  <li><a href="#goals-of-data-cleaning" id="toc-goals-of-data-cleaning" class="nav-link" data-scroll-target="#goals-of-data-cleaning">Goals of Data Cleaning</a></li>
  <li><a href="#why-some-columns-should-be-dropped" id="toc-why-some-columns-should-be-dropped" class="nav-link" data-scroll-target="#why-some-columns-should-be-dropped">Why Some Columns Should Be Dropped</a></li>
  <li><a href="#example-python-cleaning-code" id="toc-example-python-cleaning-code" class="nav-link" data-scroll-target="#example-python-cleaning-code">Example Python Cleaning Code</a></li>
  <li><a href="#handling-missing-values" id="toc-handling-missing-values" class="nav-link" data-scroll-target="#handling-missing-values">Handling Missing Values</a></li>
  <li><a href="#example-missing-value-handling" id="toc-example-missing-value-handling" class="nav-link" data-scroll-target="#example-missing-value-handling">Example Missing Value Handling</a></li>
  <li><a href="#removing-duplicate-job-postings" id="toc-removing-duplicate-job-postings" class="nav-link" data-scroll-target="#removing-duplicate-job-postings">Removing Duplicate Job Postings</a></li>
  <li><a href="#example-duplicate-removal" id="toc-example-duplicate-removal" class="nav-link" data-scroll-target="#example-duplicate-removal">Example Duplicate Removal</a></li>
  <li><a href="#why-this-matters-1" id="toc-why-this-matters-1" class="nav-link" data-scroll-target="#why-this-matters-1">Why This Matters</a></li>
  <li><a href="#output-of-cleaning-step" id="toc-output-of-cleaning-step" class="nav-link" data-scroll-target="#output-of-cleaning-step">Output of Cleaning Step</a></li>
  <li><a href="#title-exploratory-data-analysis" id="toc-title-exploratory-data-analysis" class="nav-link" data-scroll-target="#title-exploratory-data-analysis">title: “Exploratory Data Analysis”</a></li>
  <li><a href="#overview-1" id="toc-overview-1" class="nav-link" data-scroll-target="#overview-1">Overview</a></li>
  <li><a href="#defining-ai-vs-non-ai-roles" id="toc-defining-ai-vs-non-ai-roles" class="nav-link" data-scroll-target="#defining-ai-vs-non-ai-roles">Defining AI vs Non-AI Roles</a></li>
  <li><a href="#salary-distribution-ai-vs-non-ai" id="toc-salary-distribution-ai-vs-non-ai" class="nav-link" data-scroll-target="#salary-distribution-ai-vs-non-ai">Salary Distribution: AI vs Non-AI</a></li>
  <li><a href="#average-salary-by-industry-ai-vs-non-ai" id="toc-average-salary-by-industry-ai-vs-non-ai" class="nav-link" data-scroll-target="#average-salary-by-industry-ai-vs-non-ai">Average Salary by Industry: AI vs Non-AI</a></li>
  <li><a href="#top-industries-by-ai-job-posting-count" id="toc-top-industries-by-ai-job-posting-count" class="nav-link" data-scroll-target="#top-industries-by-ai-job-posting-count">Top Industries by AI Job Posting Count</a></li>
  <li><a href="#key-findings" id="toc-key-findings" class="nav-link" data-scroll-target="#key-findings">Key Findings</a></li>
  <li><a href="#overview-2" id="toc-overview-2" class="nav-link" data-scroll-target="#overview-2">Overview</a></li>
  <li><a href="#regression-model-predicting-salary" id="toc-regression-model-predicting-salary" class="nav-link" data-scroll-target="#regression-model-predicting-salary">Regression Model: Predicting Salary</a>
  <ul class="collapse">
  <li><a href="#objective-1" id="toc-objective-1" class="nav-link" data-scroll-target="#objective-1">Objective</a></li>
  <li><a href="#feature-justification" id="toc-feature-justification" class="nav-link" data-scroll-target="#feature-justification">Feature Justification</a></li>
  <li><a href="#code" id="toc-code" class="nav-link" data-scroll-target="#code">Code</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  </ul></li>
  <li><a href="#classification-model-predicting-ai-vs-non-ai-roles" id="toc-classification-model-predicting-ai-vs-non-ai-roles" class="nav-link" data-scroll-target="#classification-model-predicting-ai-vs-non-ai-roles">Classification Model: Predicting AI vs Non-AI Roles</a>
  <ul class="collapse">
  <li><a href="#objective-2" id="toc-objective-2" class="nav-link" data-scroll-target="#objective-2">Objective</a></li>
  <li><a href="#code-1" id="toc-code-1" class="nav-link" data-scroll-target="#code-1">Code</a></li>
  <li><a href="#results-1" id="toc-results-1" class="nav-link" data-scroll-target="#results-1">Results</a></li>
  <li><a href="#confusion-matrix" id="toc-confusion-matrix" class="nav-link" data-scroll-target="#confusion-matrix">Confusion Matrix</a></li>
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1">Interpretation</a></li>
  </ul></li>
  <li><a href="#kmeans-clustering-salary-tiers" id="toc-kmeans-clustering-salary-tiers" class="nav-link" data-scroll-target="#kmeans-clustering-salary-tiers">KMeans Clustering: Salary Tiers</a>
  <ul class="collapse">
  <li><a href="#objective-3" id="toc-objective-3" class="nav-link" data-scroll-target="#objective-3">Objective</a></li>
  <li><a href="#code-2" id="toc-code-2" class="nav-link" data-scroll-target="#code-2">Code</a></li>
  <li><a href="#results-2" id="toc-results-2" class="nav-link" data-scroll-target="#results-2">Results</a></li>
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2">Interpretation</a></li>
  </ul></li>
  <li><a href="#overview-3" id="toc-overview-3" class="nav-link" data-scroll-target="#overview-3">Overview</a></li>
  <li><a href="#top-skills-in-ai-roles" id="toc-top-skills-in-ai-roles" class="nav-link" data-scroll-target="#top-skills-in-ai-roles">Top Skills in AI Roles</a></li>
  <li><a href="#top-skills-in-non-ai-roles" id="toc-top-skills-in-non-ai-roles" class="nav-link" data-scroll-target="#top-skills-in-non-ai-roles">Top Skills in Non-AI Roles</a></li>
  <li><a href="#comparing-ai-and-non-ai-skill-demand" id="toc-comparing-ai-and-non-ai-skill-demand" class="nav-link" data-scroll-target="#comparing-ai-and-non-ai-skill-demand">Comparing AI and Non-AI Skill Demand</a></li>
  <li><a href="#skill-gap-assessment" id="toc-skill-gap-assessment" class="nav-link" data-scroll-target="#skill-gap-assessment">Skill Gap Assessment</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations">Recommendations</a></li>
  <li><a href="#overview-4" id="toc-overview-4" class="nav-link" data-scroll-target="#overview-4">Overview</a></li>
  <li><a href="#what-the-data-tells-us" id="toc-what-the-data-tells-us" class="nav-link" data-scroll-target="#what-the-data-tells-us">What the Data Tells Us</a></li>
  <li><a href="#recommended-career-paths" id="toc-recommended-career-paths" class="nav-link" data-scroll-target="#recommended-career-paths">Recommended Career Paths</a></li>
  <li><a href="#priority-skills-to-develop" id="toc-priority-skills-to-develop" class="nav-link" data-scroll-target="#priority-skills-to-develop">Priority Skills to Develop</a></li>
  <li><a href="#final-takeaway" id="toc-final-takeaway" class="nav-link" data-scroll-target="#final-takeaway">Final Takeaway</a></li>
  <li><a href="#ai-transparency" id="toc-ai-transparency" class="nav-link" data-scroll-target="#ai-transparency">AI Transparency</a></li>
  <li><a href="#team-contributions" id="toc-team-contributions" class="nav-link" data-scroll-target="#team-contributions">Team Contributions</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="final_report.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Career Strategy</h1>
<p class="subtitle lead">Final Report</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Manjari Kannan </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Nicholas Decesaris </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Oscar Quintero </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Boston University
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 13, 2026</p>
    </div>
  </div>
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">April 13, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<hr>
<p>title: “Personal Career Path Decisions in 2024” author: “Manjari Kannan, Nicholas Decesaris, Oscar Quintero” date: today format: html: bibliography: references.bib csl: csl/econometrica.csl toc: true docx: toc: true —</p>
<section id="objective" class="level2">
<h2 class="anchored" data-anchor-id="objective">Objective</h2>
<p>This project examines job market trends in 2024 from the perspective of job seekers rather than recruiters. Using Lightcast data, we analyze hiring patterns, salaries, skills, and labor market conditions to understand how students can position themselves more effectively.</p>
</section>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">Research Question</h2>
<p>Our project asks:</p>
<p><strong>What trends in the 2024 job market can help students and early career professionals make better career decisions?</strong></p>
</section>
<section id="why-this-matters" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters">Why This Matters</h2>
<p>Rapid changes in AI adoption, salary patterns, remote work, and employer skill expectations make the job market harder to navigate. A data driven approach helps identify which roles are growing, which skills matter most, and what kinds of jobs offer the best opportunities <span class="citation" data-cites="dominski2025advancingaicapabilitiesevolving">(<a href="#ref-dominski2025advancingaicapabilitiesevolving" role="doc-biblioref">Dominski and Lee (2025)</a>)</span>.</p>
</section>
<section id="planned-analysis" class="level2">
<h2 class="anchored" data-anchor-id="planned-analysis">Planned Analysis</h2>
<p>This project includes:</p>
<ul>
<li>data cleaning and preprocessing</li>
<li>exploratory data analysis</li>
<li>unsupervised learning with KMeans clustering</li>
<li>supervised modeling using regression and classification</li>
<li>skill gap analysis</li>
<li>career recommendations for job seekers</li>
</ul>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
</section>
<section id="overview" class="level2">
<h2 class="anchored" data-anchor-id="overview">Overview</h2>
<p>Before conducting exploratory analysis and predictive modeling, the Lightcast job postings dataset must be cleaned and standardized. Because the dataset includes many tracking variables, repeated industry and occupation code versions, and missing values, preprocessing is necessary to improve interpretability and reduce noise.</p>
</section>
<section id="goals-of-data-cleaning" class="level2">
<h2 class="anchored" data-anchor-id="goals-of-data-cleaning">Goals of Data Cleaning</h2>
<p>The main goals of data preparation are to: - remove columns that are irrelevant or redundant - keep the most current classification systems - handle missing values consistently - remove duplicate job postings - prepare the dataset for visualization and machine learning</p>
</section>
<section id="why-some-columns-should-be-dropped" class="level2">
<h2 class="anchored" data-anchor-id="why-some-columns-should-be-dropped">Why Some Columns Should Be Dropped</h2>
<p>The raw dataset contains many columns that are not useful for this project, such as URLs, duplicate tracking fields, and outdated industry and occupation code versions. Keeping too many repeated classification columns can make the analysis harder to interpret and may introduce unnecessary complexity.</p>
<p>For example, older NAICS and SOC versions are less useful when more current classifications are already available in the dataset. To keep the analysis focused and consistent, we retain the latest available fields such as <code>NAICS_2022_6</code> and <code>SOC_2021_4</code> and remove redundant older versions.</p>
</section>
<section id="example-python-cleaning-code" class="level2">
<h2 class="anchored" data-anchor-id="example-python-cleaning-code">Example Python Cleaning Code</h2>
<div id="d6539146" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql <span class="im">import</span> functions <span class="im">as</span> F</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>columns_to_drop <span class="op">=</span> [</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ID"</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"URL"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ACTIVE_URLS"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"DUPLICATES"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LAST_UPDATED_TIMESTAMP"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS2"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS3"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS4"</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS5"</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS6"</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SOC_2"</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SOC_3"</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SOC_5"</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df.drop(<span class="op">*</span>columns_to_drop)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="handling-missing-values" class="level2">
<h2 class="anchored" data-anchor-id="handling-missing-values">Handling Missing Values</h2>
<p>Missing values are common in labor market data, especially for salary and skill related fields. Different strategies should be used depending on the data type.</p>
<p>For numerical variables such as salary, replacing missing values with the median is more appropriate than using the mean because salary data is often skewed by very high paying jobs. For categorical variables, missing values can be replaced with “Unknown” so that rows are not lost unnecessarily.</p>
<p>Columns with too many missing values may also be removed if they do not provide enough useful information.</p>
</section>
<section id="example-missing-value-handling" class="level2">
<h2 class="anchored" data-anchor-id="example-missing-value-handling">Example Missing Value Handling</h2>
<div id="ebcfedd7" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>median_salary <span class="op">=</span> df_clean.approxQuantile(<span class="st">"SALARY"</span>, [<span class="fl">0.5</span>], <span class="fl">0.01</span>)[<span class="dv">0</span>]</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df_clean.fillna({</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SALARY"</span>: median_salary,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"REMOTE_TYPE_NAME"</span>: <span class="st">"Unknown"</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"NAICS_2022_6_NAME"</span>: <span class="st">"Unknown"</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"SOC_2021_4_NAME"</span>: <span class="st">"Unknown"</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="removing-duplicate-job-postings" class="level2">
<h2 class="anchored" data-anchor-id="removing-duplicate-job-postings">Removing Duplicate Job Postings</h2>
<p>Duplicate job postings can distort the results by counting the same opportunity multiple times. To prevent this, duplicate observations should be removed using a reasonable combination of identifying fields such as title, company, location, and posting date.</p>
</section>
<section id="example-duplicate-removal" class="level2">
<h2 class="anchored" data-anchor-id="example-duplicate-removal">Example Duplicate Removal</h2>
<div id="27530371" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df_clean.dropDuplicates([</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"TITLE"</span>,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"COMPANY_NAME"</span>,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"LOCATION"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"POSTED"</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="why-this-matters-1" class="level2">
<h2 class="anchored" data-anchor-id="why-this-matters-1">Why This Matters</h2>
<p>Data cleaning improves the reliability of every later stage of the project. Cleaner data leads to:</p>
<ul>
<li>more accurate summaries and charts</li>
<li>better model performance</li>
<li>clearer interpretation for job seekers</li>
<li>more trustworthy career recommendations</li>
</ul>
</section>
<section id="output-of-cleaning-step" class="level2">
<h2 class="anchored" data-anchor-id="output-of-cleaning-step">Output of Cleaning Step</h2>
<p>After cleaning, the dataset is more suitable for:</p>
<ul>
<li>exploratory analysis of salary, industry, and remote work patterns</li>
<li>clustering by occupation or industry categories</li>
<li>regression models predicting salary</li>
<li>classification models predicting job categories or remote work type</li>
</ul>
<hr>
</section>
<section id="title-exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="title-exploratory-data-analysis">title: “Exploratory Data Analysis”</h2>
</section>
<section id="overview-1" class="level2">
<h2 class="anchored" data-anchor-id="overview-1">Overview</h2>
<p>Before building any models, we explored the Lightcast job postings dataset to understand the underlying patterns in salary, industry composition, and AI-related job demand. This section summarizes what the data revealed about how AI roles compare to non-AI roles across key dimensions.</p>
<p>All analysis is based on the cleaned dataset of 70,892 job postings.</p>
</section>
<section id="defining-ai-vs-non-ai-roles" class="level2">
<h2 class="anchored" data-anchor-id="defining-ai-vs-non-ai-roles">Defining AI vs Non-AI Roles</h2>
<p>To distinguish AI-related jobs from the rest of the dataset, we flagged any posting where the job title or skills field contained keywords such as “ai”, “machine learning”, “artificial intelligence”, “deep learning”, “data science”, “nlp”, “llm”, or “neural network”.</p>
<div id="3b6b7208" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> col, when, lower</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>ai_keywords <span class="op">=</span> <span class="st">"ai|machine learning|artificial intelligence|deep learning|nlp|llm|data science|neural network"</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>df_clean <span class="op">=</span> df_clean.withColumn(</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"IS_AI_ROLE"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    when(</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        lower(col(<span class="st">"TITLE_RAW"</span>)).rlike(ai_keywords) <span class="op">|</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>        lower(col(<span class="st">"SKILLS_NAME"</span>)).rlike(ai_keywords),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        <span class="dv">1</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    ).otherwise(<span class="dv">0</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>df_clean.groupBy(<span class="st">"IS_AI_ROLE"</span>).count().show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<pre><code>+----------+-----+
|IS_AI_ROLE|count|
+----------+-----+
|         1|31857|
|         0|39035|
+----------+-----+</code></pre>
<p>This produced 31,857 AI-related postings (approximately 45% of the dataset) and 39,035 non-AI postings (approximately 55%). The near-even split suggests that AI-related roles have moved well beyond a niche segment of the labor market.</p>
</section>
<section id="salary-distribution-ai-vs-non-ai" class="level2">
<h2 class="anchored" data-anchor-id="salary-distribution-ai-vs-non-ai">Salary Distribution: AI vs Non-AI</h2>
<div id="2d4ae0a6" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>salary_df <span class="op">=</span> df_clean.select(<span class="st">"SALARY_MID"</span>, <span class="st">"IS_AI_ROLE"</span>) <span class="op">\</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"SALARY_MID"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    .toPandas()</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>salary_df[<span class="st">"Role Type"</span>] <span class="op">=</span> salary_df[<span class="st">"IS_AI_ROLE"</span>].<span class="bu">map</span>({<span class="dv">0</span>: <span class="st">"Non-AI"</span>, <span class="dv">1</span>: <span class="st">"AI"</span>})</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> px.histogram(</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    salary_df, x<span class="op">=</span><span class="st">"SALARY_MID"</span>, color<span class="op">=</span><span class="st">"Role Type"</span>, barmode<span class="op">=</span><span class="st">"overlay"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    nbins<span class="op">=</span><span class="dv">50</span>, opacity<span class="op">=</span><span class="fl">0.7</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    title<span class="op">=</span><span class="st">"Salary Distribution: AI vs Non-AI Roles"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    labels<span class="op">=</span>{<span class="st">"SALARY_MID"</span>: <span class="st">"Salary (USD)"</span>}</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>fig.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<iframe src="outputs/salary_distribution.html" width="100%" height="500px" frameborder="0"></iframe>
<p>The first question we investigated was whether AI roles simply pay more. The overall pattern suggests they do not, at least not uniformly.</p>
<p>Both distributions peak near $112,500 and follow a similar right-skewed shape. The two groups overlap substantially, which indicates that holding an AI-related title does not automatically translate into higher compensation. The relationship between AI and salary appears to be more complex than a simple premium.</p>
</section>
<section id="average-salary-by-industry-ai-vs-non-ai" class="level2">
<h2 class="anchored" data-anchor-id="average-salary-by-industry-ai-vs-non-ai">Average Salary by Industry: AI vs Non-AI</h2>
<div id="ce1a5e24" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> <span class="bu">round</span> <span class="im">as</span> spark_round</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>industry_df <span class="op">=</span> df_clean.groupBy(<span class="st">"NAICS_2022_2_NAME"</span>, <span class="st">"IS_AI_ROLE"</span>) <span class="op">\</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    .avg(<span class="st">"SALARY_MID"</span>) <span class="op">\</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    .withColumn(<span class="st">"avg_salary"</span>, spark_round(<span class="st">"avg(SALARY_MID)"</span>, <span class="dv">0</span>)) <span class="op">\</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"NAICS_2022_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    .orderBy(<span class="st">"NAICS_2022_2_NAME"</span>, <span class="st">"IS_AI_ROLE"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>industry_df.select(<span class="st">"NAICS_2022_2_NAME"</span>, <span class="st">"IS_AI_ROLE"</span>, <span class="st">"avg_salary"</span>).show(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<pre><code>+--------------------+----------+----------+
|    NAICS_2022_2_NAME|IS_AI_ROLE|avg_salary|
+--------------------+----------+----------+
|Accommodation and...|         0|  119421.0|
|Accommodation and...|         1|  116452.0|
|Administrative an...|         0|  107157.0|
|Administrative an...|         1|  107751.0|
|Agriculture, Fore...|         0|  106967.0|
|Agriculture, Fore...|         1|  106178.0|
|Arts, Entertainme...|         0|   92280.0|
|Arts, Entertainme...|         1|  105354.0|
|Construction      |         0|  103011.0|
|Construction      |         1|  116595.0|
+--------------------+----------+----------+</code></pre>
<iframe src="outputs/salary_by_industry.html" width="100%" height="600px" frameborder="0"></iframe>
<p>Breaking salary down by industry reveals a more nuanced picture. Certain industries show a meaningful AI salary premium, including Arts and Entertainment (approximately +$13,000), Construction (approximately +$13,500), and Retail Trade (approximately +$9,000). In these fields, AI skills remain relatively uncommon, and compensation reflects that scarcity.</p>
<p>In contrast, the Information industry pays AI roles less on average than non-AI roles. Interestingly, “working in an occupation that is considered high skill increases the odds of job loss to AI <span class="citation" data-cites="doi:10.1177/23780231241259672">(<a href="#ref-doi:10.1177/23780231241259672" role="doc-biblioref">Dahlin (2024)</a>)</span>”…especially for the “middle-skill employees in the technological landscape <span class="citation" data-cites="doi:10.1177/23780231241259672">(<a href="#ref-doi:10.1177/23780231241259672" role="doc-biblioref">Dahlin (2024)</a>)</span>.” Arguably, the high-skill employees can pivot using tools and higher levels of resources and knowledge to adapt to the shifting environment which does not appear to directly impact salary until it is considered that the majority of the middle-skill employees will must either transition to another field or be entirely displaced. This apparent stability of salary is likely because of the traditional IT and enterprise infrastructure roles in that sector already commanding high salaries, making AI titles less financially distinctive by comparison due to the stability of the high-skill employees maintaining positions.</p>
</section>
<section id="top-industries-by-ai-job-posting-count" class="level2">
<h2 class="anchored" data-anchor-id="top-industries-by-ai-job-posting-count">Top Industries by AI Job Posting Count</h2>
<div id="a33c2b92" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.sql.functions <span class="im">import</span> desc</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>top_industries <span class="op">=</span> df_clean.<span class="bu">filter</span>(col(<span class="st">"IS_AI_ROLE"</span>) <span class="op">==</span> <span class="dv">1</span>) <span class="op">\</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"NAICS_2022_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    .groupBy(<span class="st">"NAICS_2022_2_NAME"</span>) <span class="op">\</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    .count() <span class="op">\</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    .orderBy(desc(<span class="st">"count"</span>)) <span class="op">\</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    .limit(<span class="dv">10</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>top_industries.show(truncate<span class="op">=</span><span class="va">False</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<pre><code>+--------------------------------------------------------+-----+
|NAICS_2022_2_NAME                                       |count|
+--------------------------------------------------------+-----+
|Professional, Scientific, and Technical Services        |9821 |
|Finance and Insurance                                   |4932 |
|Information                                             |3847 |
|Management of Companies and Enterprises                 |2841 |
|Manufacturing                                           |2134 |
|Administrative and Support and Waste Management...      |1823 |
|Health Care and Social Assistance                       |1654 |
|Retail Trade                                            |1432 |
|Educational Services                                    |1187 |
|Unclassified Industry                                   |1001 |
+--------------------------------------------------------+-----+</code></pre>
<iframe src="outputs/top_industries.html" width="100%" height="500px" frameborder="0"></iframe>
<p>In terms of where AI jobs are being posted, Professional, Scientific, and Technical Services leads by a wide margin, followed by Finance and Insurance and Information. While AI-related roles appear across many sectors, the majority of active hiring remains concentrated in knowledge-intensive industries. For job seekers targeting AI roles, these sectors represent the highest volume of opportunity.</p>
</section>
<section id="key-findings" class="level2">
<h2 class="anchored" data-anchor-id="key-findings">Key Findings</h2>
<p>Several patterns emerged from this exploratory analysis worth carrying forward into the modeling phase.</p>
<p>The overall salary difference between AI and non-AI roles is insignificant at roughly $100 on average. The salary premium associated with AI skills is industry-specific rather than universal. Fields where AI capabilities are still emerging tend to reward those skills more generously. The concentration of AI hiring in professional services, finance, and information suggests that the benefits of AI are not evenly distributed across the workforce. Where a worker is employed matters as much as what skills they bring.</p>
</section>
<section id="overview-2" class="level2">
<h2 class="anchored" data-anchor-id="overview-2">Overview</h2>
<p>This section applies three machine learning models to the cleaned Lightcast dataset: a linear regression model to predict salary, a logistic regression model to classify AI versus non-AI roles, and a KMeans clustering model to identify natural salary tiers across the job market.</p>
</section>
<section id="regression-model-predicting-salary" class="level2">
<h2 class="anchored" data-anchor-id="regression-model-predicting-salary">Regression Model: Predicting Salary</h2>
<section id="objective-1" class="level3">
<h3 class="anchored" data-anchor-id="objective-1">Objective</h3>
<p>The goal of this model is to predict the midpoint salary of a job posting based on observable job characteristics.</p>
</section>
<section id="feature-justification" class="level3">
<h3 class="anchored" data-anchor-id="feature-justification">Feature Justification</h3>
<p>Two versions of the model were tested. The first used industry, remote work type, and AI role flag as features. The second added occupation category and years of experience. Occupation category was expected to be the strongest predictor because salary varies substantially across professional fields regardless of industry.</p>
</section>
<section id="code" class="level3">
<h3 class="anchored" data-anchor-id="code">Code</h3>
<div id="06ad8cee" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.feature <span class="im">import</span> StringIndexer, VectorAssembler</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.regression <span class="im">import</span> LinearRegression</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml <span class="im">import</span> Pipeline</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> RegressionEvaluator</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Model 2: industry + remote + occupation + experience + AI flag</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>df_model <span class="op">=</span> df_clean.<span class="bu">filter</span>(col(<span class="st">"SALARY_MID"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"NAICS_2022_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"REMOTE_TYPE_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"SOC_2021_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    .withColumn(<span class="st">"MIN_YEARS_EXP"</span>, col(<span class="st">"MIN_YEARS_EXPERIENCE"</span>).cast(<span class="st">"double"</span>)) <span class="op">\</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    .fillna({<span class="st">"MIN_YEARS_EXP"</span>: <span class="fl">0.0</span>})</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>industry_indexer <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"NAICS_2022_2_NAME"</span>, outputCol<span class="op">=</span><span class="st">"industry_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>remote_indexer <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"REMOTE_TYPE_NAME"</span>, outputCol<span class="op">=</span><span class="st">"remote_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>soc_indexer <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"SOC_2021_2_NAME"</span>, outputCol<span class="op">=</span><span class="st">"soc_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>assembler <span class="op">=</span> VectorAssembler(</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>[<span class="st">"industry_idx"</span>, <span class="st">"remote_idx"</span>, <span class="st">"soc_idx"</span>, <span class="st">"IS_AI_ROLE"</span>, <span class="st">"MIN_YEARS_EXP"</span>],</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features"</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>lr <span class="op">=</span> LinearRegression(featuresCol<span class="op">=</span><span class="st">"features"</span>, labelCol<span class="op">=</span><span class="st">"SALARY_MID"</span>)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>pipeline <span class="op">=</span> Pipeline(stages<span class="op">=</span>[industry_indexer, remote_indexer, soc_indexer, assembler, lr])</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>train, test <span class="op">=</span> df_model.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> pipeline.fit(train)</span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a>predictions <span class="op">=</span> model.transform(test)</span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>rmse <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY_MID"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"rmse"</span>).evaluate(predictions)</span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>r2 <span class="op">=</span> RegressionEvaluator(labelCol<span class="op">=</span><span class="st">"SALARY_MID"</span>, predictionCol<span class="op">=</span><span class="st">"prediction"</span>, metricName<span class="op">=</span><span class="st">"r2"</span>).evaluate(predictions)</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE: $</span><span class="sc">{</span>rmse<span class="sc">:,.0f}</span><span class="ss">"</span>)</span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R2: </span><span class="sc">{</span>r2<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="results" class="level3">
<h3 class="anchored" data-anchor-id="results">Results</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model</th>
<th>Features</th>
<th>RMSE</th>
<th>R2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model 1</td>
<td>Industry, Remote Type, AI Flag</td>
<td>$31,428</td>
<td>0.0094</td>
</tr>
<tr class="even">
<td>Model 2</td>
<td>+ Occupation, Experience</td>
<td>$30,040</td>
<td>0.0949</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretation" class="level3">
<h3 class="anchored" data-anchor-id="interpretation">Interpretation</h3>
<p>Adding occupation category and experience improved R2 from 0.009 to 0.095 and reduced RMSE by roughly $1,400. The overall explanatory power remains modest, which is expected given that salary is also shaped by factors not present in this dataset such as company size, specific technical skills, and education level.</p>
</section>
</section>
<section id="classification-model-predicting-ai-vs-non-ai-roles" class="level2">
<h2 class="anchored" data-anchor-id="classification-model-predicting-ai-vs-non-ai-roles">Classification Model: Predicting AI vs Non-AI Roles</h2>
<section id="objective-2" class="level3">
<h3 class="anchored" data-anchor-id="objective-2">Objective</h3>
<p>This model attempts to classify whether a job posting is AI-related based on industry, remote work type, and occupation category.</p>
</section>
<section id="code-1" class="level3">
<h3 class="anchored" data-anchor-id="code-1">Code</h3>
<div id="80b94adf" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.classification <span class="im">import</span> LogisticRegression</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.evaluation <span class="im">import</span> MulticlassClassificationEvaluator, BinaryClassificationEvaluator</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>df_clf <span class="op">=</span> df_clean.<span class="bu">filter</span>(col(<span class="st">"NAICS_2022_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"REMOTE_TYPE_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"SOC_2021_2_NAME"</span>).isNotNull())</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>industry_idx <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"NAICS_2022_2_NAME"</span>, outputCol<span class="op">=</span><span class="st">"industry_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>remote_idx <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"REMOTE_TYPE_NAME"</span>, outputCol<span class="op">=</span><span class="st">"remote_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>soc_idx <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"SOC_2021_2_NAME"</span>, outputCol<span class="op">=</span><span class="st">"soc_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>assembler_clf <span class="op">=</span> VectorAssembler(inputCols<span class="op">=</span>[<span class="st">"industry_idx"</span>, <span class="st">"remote_idx"</span>, <span class="st">"soc_idx"</span>], outputCol<span class="op">=</span><span class="st">"features"</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>lrc <span class="op">=</span> LogisticRegression(featuresCol<span class="op">=</span><span class="st">"features"</span>, labelCol<span class="op">=</span><span class="st">"IS_AI_ROLE"</span>, maxIter<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>pipeline_clf <span class="op">=</span> Pipeline(stages<span class="op">=</span>[industry_idx, remote_idx, soc_idx, assembler_clf, lrc])</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>train_clf, test_clf <span class="op">=</span> df_clf.randomSplit([<span class="fl">0.8</span>, <span class="fl">0.2</span>], seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>model_clf <span class="op">=</span> pipeline_clf.fit(train_clf)</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>predictions_clf <span class="op">=</span> model_clf.transform(test_clf)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>predictions_clf.groupBy(<span class="st">"IS_AI_ROLE"</span>, <span class="st">"prediction"</span>).count().orderBy(<span class="st">"IS_AI_ROLE"</span>, <span class="st">"prediction"</span>).show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="results-1" class="level3">
<h3 class="anchored" data-anchor-id="results-1">Results</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Accuracy</td>
<td>55.6%</td>
</tr>
<tr class="even">
<td>F1 Score</td>
<td>0.48</td>
</tr>
<tr class="odd">
<td>AUC</td>
<td>0.54</td>
</tr>
</tbody>
</table>
</section>
<section id="confusion-matrix" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrix">Confusion Matrix</h3>
<pre><code>+----------+----------+-----+
|IS_AI_ROLE|prediction|count|
+----------+----------+-----+
|         0|       0.0| 6869|
|         0|       1.0|  825|
|         1|       0.0| 5426|
|         1|       1.0|  952|
+----------+----------+-----+</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="outputs/confusion_matrix.png" class="img-fluid figure-img"></p>
<figcaption>Confusion Matrix</figcaption>
</figure>
</div>
<p>The confusion matrix shows that the model correctly identifies most non-AI roles (6,869 true negatives) but misclassifies the majority of actual AI roles as non-AI (5,426 false negatives). This pattern reflects the core finding that AI roles are not structurally distinguishable from non-AI roles based on industry, remote type, and occupation category alone.</p>
</section>
<section id="interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-1">Interpretation</h3>
<p>The model performs only slightly better than random guessing. This suggests that AI-related roles are spread across industries and occupation categories rather than being concentrated in obvious segments. The distinction between AI and non-AI roles lives primarily in the specific skills and title language of the posting, not in its structural characteristics.</p>
</section>
</section>
<section id="kmeans-clustering-salary-tiers" class="level2">
<h2 class="anchored" data-anchor-id="kmeans-clustering-salary-tiers">KMeans Clustering: Salary Tiers</h2>
<section id="objective-3" class="level3">
<h3 class="anchored" data-anchor-id="objective-3">Objective</h3>
<p>KMeans clustering was used to identify natural groupings in the job market based on industry, occupation, salary, and AI role status.</p>
</section>
<section id="code-2" class="level3">
<h3 class="anchored" data-anchor-id="code-2">Code</h3>
<div id="a87c079a" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyspark.ml.clustering <span class="im">import</span> KMeans</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>df_km <span class="op">=</span> df_clean.<span class="bu">filter</span>(col(<span class="st">"NAICS_2022_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"SOC_2021_2_NAME"</span>).isNotNull()) <span class="op">\</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    .<span class="bu">filter</span>(col(<span class="st">"SALARY_MID"</span>).isNotNull())</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>industry_km <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"NAICS_2022_2_NAME"</span>, outputCol<span class="op">=</span><span class="st">"industry_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>soc_km <span class="op">=</span> StringIndexer(inputCol<span class="op">=</span><span class="st">"SOC_2021_2_NAME"</span>, outputCol<span class="op">=</span><span class="st">"soc_idx"</span>, handleInvalid<span class="op">=</span><span class="st">"skip"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>assembler_km <span class="op">=</span> VectorAssembler(</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    inputCols<span class="op">=</span>[<span class="st">"industry_idx"</span>, <span class="st">"soc_idx"</span>, <span class="st">"SALARY_MID"</span>, <span class="st">"IS_AI_ROLE"</span>],</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    outputCol<span class="op">=</span><span class="st">"features"</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>kmeans <span class="op">=</span> KMeans(featuresCol<span class="op">=</span><span class="st">"features"</span>, k<span class="op">=</span><span class="dv">4</span>, seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>pipeline_km <span class="op">=</span> Pipeline(stages<span class="op">=</span>[industry_km, soc_km, assembler_km, kmeans])</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>model_km <span class="op">=</span> pipeline_km.fit(df_km)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>clusters <span class="op">=</span> model_km.transform(df_km)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>clusters.groupBy(<span class="st">"prediction"</span>, <span class="st">"IS_AI_ROLE"</span>) <span class="op">\</span></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    .avg(<span class="st">"SALARY_MID"</span>) <span class="op">\</span></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    .orderBy(<span class="st">"prediction"</span>, <span class="st">"IS_AI_ROLE"</span>) <span class="op">\</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    .show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
</section>
<section id="results-2" class="level3">
<h3 class="anchored" data-anchor-id="results-2">Results</h3>
<pre><code>+----------+----------+------------------+
|prediction|IS_AI_ROLE|   avg(SALARY_MID)|
+----------+----------+------------------+
|         0|         0| 82527.93027166883|
|         0|         1| 82259.38657105606|
|         1|         0|114743.48156257602|
|         1|         1|114706.52900810979|
|         2|         0|177965.12350242163|
|         2|         1| 180190.9214202561|
|         3|         0| 47270.14509564509|
|         3|         1| 50669.67723880597|
+----------+----------+------------------+</code></pre>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cluster</th>
<th>Avg Salary (Non-AI)</th>
<th>Avg Salary (AI)</th>
<th>Job Count</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Entry Level</td>
<td>$47,270</td>
<td>$50,670</td>
<td>4,601</td>
</tr>
<tr class="even">
<td>Mid Level</td>
<td>$82,528</td>
<td>$82,259</td>
<td>7,700</td>
</tr>
<tr class="odd">
<td>Upper Mid Level</td>
<td>$114,743</td>
<td>$114,707</td>
<td>51,215</td>
</tr>
<tr class="even">
<td>Senior Level</td>
<td>$177,965</td>
<td>$180,191</td>
<td>7,359</td>
</tr>
</tbody>
</table>
</section>
<section id="interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="interpretation-2">Interpretation</h3>
<p>The clustering produced four well-separated salary tiers. The most striking pattern is that within every cluster, AI and non-AI roles earn nearly identical average salaries. The salary tier a job belongs to is determined by its occupation and industry profile, not by whether it involves AI. This finding is consistent across all three models: AI designation alone does not drive salary. Structural job characteristics and market positioning matter more.</p>
</section>
</section>
<section id="overview-3" class="level2">
<h2 class="anchored" data-anchor-id="overview-3">Overview</h2>
<p>This section examines which skills are most in demand across AI and non-AI job postings in the Lightcast dataset, and compares those findings to the skill profile of a typical business analytics student. The goal is to identify where gaps exist and what students should prioritize to remain competitive in an AI-influenced job market.</p>
</section>
<section id="top-skills-in-ai-roles" class="level2">
<h2 class="anchored" data-anchor-id="top-skills-in-ai-roles">Top Skills in AI Roles</h2>
<p>The fifteen most frequently requested skills across AI-related job postings are listed below.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Skill</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Communication</td>
<td>16,483</td>
</tr>
<tr class="even">
<td>Data Analysis</td>
<td>15,188</td>
</tr>
<tr class="odd">
<td>Management</td>
<td>12,316</td>
</tr>
<tr class="even">
<td>Detail Oriented</td>
<td>11,753</td>
</tr>
<tr class="odd">
<td>SQL</td>
<td>11,717</td>
</tr>
<tr class="even">
<td>Problem Solving</td>
<td>10,351</td>
</tr>
<tr class="odd">
<td>Computer Science</td>
<td>9,535</td>
</tr>
<tr class="even">
<td>Leadership</td>
<td>8,852</td>
</tr>
<tr class="odd">
<td>Python</td>
<td>7,600</td>
</tr>
<tr class="even">
<td>Operations</td>
<td>7,299</td>
</tr>
<tr class="odd">
<td>Microsoft Excel</td>
<td>7,057</td>
</tr>
<tr class="even">
<td>Tableau</td>
<td>6,904</td>
</tr>
<tr class="odd">
<td>Data Science</td>
<td>6,617</td>
</tr>
<tr class="even">
<td>Dashboard</td>
<td>6,529</td>
</tr>
<tr class="odd">
<td>Project Management</td>
<td>6,266</td>
</tr>
</tbody>
</table>
</section>
<section id="top-skills-in-non-ai-roles" class="level2">
<h2 class="anchored" data-anchor-id="top-skills-in-non-ai-roles">Top Skills in Non-AI Roles</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Skill</th>
<th>Frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Communication</td>
<td>14,621</td>
</tr>
<tr class="even">
<td>Data Analysis</td>
<td>12,502</td>
</tr>
<tr class="odd">
<td>Management</td>
<td>11,813</td>
</tr>
<tr class="even">
<td>SQL</td>
<td>9,429</td>
</tr>
<tr class="odd">
<td>Leadership</td>
<td>8,350</td>
</tr>
<tr class="even">
<td>Problem Solving</td>
<td>7,715</td>
</tr>
<tr class="odd">
<td>Project Management</td>
<td>7,209</td>
</tr>
<tr class="even">
<td>Computer Science</td>
<td>7,133</td>
</tr>
<tr class="odd">
<td>Business Process</td>
<td>6,998</td>
</tr>
<tr class="even">
<td>Operations</td>
<td>6,993</td>
</tr>
<tr class="odd">
<td>SAP Applications</td>
<td>6,821</td>
</tr>
<tr class="even">
<td>Business Requirements</td>
<td>6,726</td>
</tr>
<tr class="odd">
<td>Finance</td>
<td>6,147</td>
</tr>
<tr class="even">
<td>Presentations</td>
<td>5,763</td>
</tr>
<tr class="odd">
<td>Planning</td>
<td>5,621</td>
</tr>
</tbody>
</table>
</section>
<section id="comparing-ai-and-non-ai-skill-demand" class="level2">
<h2 class="anchored" data-anchor-id="comparing-ai-and-non-ai-skill-demand">Comparing AI and Non-AI Skill Demand</h2>
<p>Several patterns emerge when comparing the two lists. Communication, Data Analysis, Management, SQL, and Problem Solving rank highly in both, confirming that these are foundational skills regardless of whether a role is AI-related. However, AI roles place noticeably higher demand on Python, Tableau, Data Science, and Dashboard skills, while non-AI roles emphasize SAP Applications, Business Requirements, Finance, and Business Process knowledge.</p>
<p>This suggests that the transition into AI-related work requires building on a shared analytical foundation while adding more specialized technical and data visualization capabilities.</p>
</section>
<section id="skill-gap-assessment" class="level2">
<h2 class="anchored" data-anchor-id="skill-gap-assessment">Skill Gap Assessment</h2>
<p>A typical business analytics graduate entering this job market is likely comfortable with communication, Excel, SQL, and basic data analysis. Based on the demand patterns observed in this dataset, the most significant gaps tend to fall in the following areas.</p>
<p>Python programming appears in the top ten for AI roles but not at all in the non-AI top fifteen, making it one of the clearest differentiators for students targeting AI-related positions. Tableau and dashboard development are heavily requested in AI roles and represent a practical visualization skill that complements SQL and Excel. Data Science as a named competency appears frequently in AI postings and signals employer expectations around modeling, statistical reasoning, and analytical workflows beyond basic reporting.</p>
<p>On the non-AI side, familiarity with enterprise platforms such as SAP and business process documentation skills appear prominently, suggesting that students targeting traditional analyst or operations roles should also develop comfort with enterprise systems.</p>
</section>
<section id="recommendations" class="level2">
<h2 class="anchored" data-anchor-id="recommendations">Recommendations</h2>
<p>Students aiming for AI-related roles should prioritize Python, Tableau, and applied data science coursework. Those targeting traditional business or operations roles will benefit from developing familiarity with SAP and structured business process skills. In either path, SQL, communication, and analytical thinking remain the most universally valued capabilities in the current labor market.</p>
</section>
<section id="overview-4" class="level2">
<h2 class="anchored" data-anchor-id="overview-4">Overview</h2>
<p>This section translates the findings from our exploratory analysis, predictive modeling, and skill gap assessment into actionable career guidance for students and early-career job seekers navigating an AI-influenced labor market.</p>
</section>
<section id="what-the-data-tells-us" class="level2">
<h2 class="anchored" data-anchor-id="what-the-data-tells-us">What the Data Tells Us</h2>
<p>Several consistent findings emerged across all stages of this project that should directly inform career planning decisions.</p>
<p>AI-related roles do not universally pay more. Recent studies suggest that “increased AI exposure may be correlated with higher earnings in some contexts, but the strength and direction of this relationship are sensitive to model specification[s] <span class="citation" data-cites="dominski2025advancingaicapabilitiesevolving">(<a href="#ref-dominski2025advancingaicapabilitiesevolving" role="doc-biblioref">Dominski and Lee (2025)</a>)</span>.” Within the findings of this project, for instance, the average salary difference between AI and non-AI roles in this dataset is approximately $100, which is negligible. Salary is determined more by industry, occupation tier, and job level than by AI designation alone. Students who assume that adding AI skills to their resume will automatically lead to higher pay may be disappointed without also considering the sector and role level they are targeting.</p>
<p>The salary premium for AI skills is industry-specific. Fields such as Arts and Entertainment, Construction, and Retail Trade show AI salary premiums of $9,000 to $13,500, likely because AI capabilities remain scarce in those sectors. In contrast, the Information industry pays non-AI roles more on average because that sector already compensates technical work highly regardless of AI involvement. Job seekers should research salary norms within their target industry rather than relying on general AI salary narratives.</p>
<p>Salary tier matters more than AI status. The KMeans clustering analysis identified four distinct salary tiers in the job market ranging from approximately $49,000 at the entry level to $179,000 at the senior level. Within every tier, AI and non-AI roles earn nearly identical salaries. Moving up a salary tier requires developing the occupation and industry profile associated with that tier, not simply acquiring AI-related keywords.</p>
</section>
<section id="recommended-career-paths" class="level2">
<h2 class="anchored" data-anchor-id="recommended-career-paths">Recommended Career Paths</h2>
<p>Based on the skill demand patterns and salary distributions observed in this dataset, three career directions appear particularly well-suited for business analytics students.</p>
<p>Students with strong SQL, Python, and data visualization skills are well positioned for data science and analytics roles, which appear frequently in the Professional, Scientific, and Technical Services sector and consistently fall in the upper mid salary tier around $114,000.</p>
<p>Students interested in finance and insurance will find that sector offers strong AI role concentration and competitive salaries. Finance-adjacent analytical roles that combine business knowledge with data skills appear to be in high demand.</p>
<p>Students targeting non-AI paths should not overlook the value of enterprise systems experience. SAP, business process management, and ERP skills appear prominently in non-AI postings and are associated with stable demand across multiple industries.</p>
</section>
<section id="priority-skills-to-develop" class="level2">
<h2 class="anchored" data-anchor-id="priority-skills-to-develop">Priority Skills to Develop</h2>
<p>Based on the skill gap analysis, the highest-return skills for students to develop before entering the job market are Python programming, SQL, Tableau or equivalent dashboard tools, and applied data science competencies. Communication, problem solving, and project management round out the universal skills that employers expect regardless of role type.</p>
</section>
<section id="final-takeaway" class="level2">
<h2 class="anchored" data-anchor-id="final-takeaway">Final Takeaway</h2>
<p>The rise of AI is reshaping the job market, but not in the simple way that headlines often suggest. Our analysis shows that AI skills matter most in specific industries and role contexts, that salary outcomes depend heavily on occupation tier and sector, and that foundational analytical skills remain the most consistently valued capabilities across the entire labor market. Students who build a strong analytical foundation and develop targeted technical skills for their chosen industry will be better positioned than those who chase AI credentials without strategic direction.</p>
</section>
<section id="ai-transparency" class="level2">
<h2 class="anchored" data-anchor-id="ai-transparency">AI Transparency</h2>
<p>This project used Claude (Sonnet 4.6, Anthropic) as an AI assistant throughout process. Specifically, Claude was used to assist with PySpark syntax and debugging, resolving data pipeline errors such as CSV column misalignment and salary column misidentification (the SALARY column was discovered to contain SOC occupation codes rather than numeric values, requiring a pivot to SALARY_FROM and SALARY_TO), casting errors when converting string fields to numeric types, structuring and formatting Quarto markdown pages, identifying grammatical errors and suggesting improvements to written analysis, and providing guidance on machine learning model evaluation and visualization.</p>
<p>For concepts and workflows that were new, such as building ML pipelines with StringIndexer and VectorAssembler, and enabling code folding in Quarto, the professor’s lecture videos were the primary reference. Claude was used moreso when errors happened during implementation or when troubleshooting was needed, such as fixing the git history after large files were accidentally committed, resolving the kaleido and Chrome installation required for Plotly image export, and correcting citation key mismatches in the BibTeX file.</p>
<p>All analytical decisions, including the choice of research question, feature selection, model interpretation, and conclusions drawn from the data, were made by Manjari Kannan.</p>
</section>
<section id="team-contributions" class="level2">
<h2 class="anchored" data-anchor-id="team-contributions">Team Contributions</h2>
<ul>
<li><strong>Manjari Kannan</strong> : built the Quarto website structure and navigation, handled data cleaning and preprocessing in PySpark including salary column identification, missing value imputation, and duplicate removal, developed the AI vs Non-AI role classification using keyword matching, conducted exploratory data analysis across salary, industry, and job posting trends, built and evaluated the regression, classification, and clustering models, completed the skill gap analysis, wrote the analysis and interpretation for each section of the report, converted visualizations to interactive Plotly charts, and managed GitHub throughout the project</li>
<li><strong>Oscar Quintero</strong> : sourced and formatted the academic references in BibTeX, helped in managing the website aesthetic and overall formatting</li>
<li><strong>Nicholas Decesaris</strong> : responsible for the final presentation</li>
</ul>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-doi:10.1177/23780231241259672" class="csl-entry" role="listitem">
<span class="smallcaps">Dahlin, E.</span> (2024): <span>“<a href="https://doi.org/10.1177/23780231241259672">Who says artificial intelligence is stealing our jobs?</a>”</span> <em>Socius</em>, 10, 23780231241259672.
</div>
<div id="ref-dominski2025advancingaicapabilitiesevolving" class="csl-entry" role="listitem">
<span class="smallcaps">Dominski, J., and Y. S. Lee</span>. (2025): <span>“<a href="https://arxiv.org/abs/2507.08244">Advancing AI Capabilities and Evolving Labor Outcomes</a>,”</span>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/manjarikannan\.github\.io\/AD688-Sp26-O2-Group1-Job-Market-Analysis-2024\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>